### ISSUE TITLE
Base names in short bakctrace 

### ISSUE THREAD

**Issue by jfilak** [abrt/satyr#253]
Short backtrace should not include absolute file system paths.

The following short backtrace:
```
#1 crash in /usr/bin/will_segfault
#2 varargs in /usr/bin/will_segfault
#3 f in /usr/bin/will_segfault
#4 callback in /usr/bin/will_segfault
#5 call_me_back in /usr/lib64/libwillcrash.so.0.0.0
```

should look like this one:
```
#1 crash in will_segfault
#2 varargs in will_segfault
#3 f in will_segfault
#4 callback in will_segfault
#5 call_me_back in libwillcrash.so.0.0.0
```

What about to changed the format to:
```
#1 [will_segfault] crash 
#2 [will_segfault] varargs
#3 [will_segfault] f
#4 [will_segfault] callback
#5 [libwillcrash.so.0.0.0] call_me_back
```

**Comment by juliusmilan** [comment]
why not to include absolute paths? it occurs to produce very long lines?
I think that from third example, without knowledge that "will_segfault" is an executable and "f", "crash", ... are procedures it would not be obvious, on the other hand this format ease file name recognition since it is aligned, what about:

#1 [/usr/bin/will_segfault] crash 
#2 [/usr/bin/will_segfault] varargs
#3 [/usr/bin/will_segfault] f
#4 [/usr/bin/will_segfault] callback
#5 [/usr/lib64/libwillcrash.so.0.0.0] call_me_back

but also worth to consider, if procedure name isn't more important than file name and therfore should be first
